#!/bin/bash

# alignement using megacc

local=$(pwd)

mkdir alignement

cd alignement

cat <<EOF > muscle_align_protein.mao 
; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using MEGA.
[ MEGAinfo ]
ver                               = 11220624-x86_64 Linux            
[ DataSettings ]
datatype                          = snProtein                        
missingBaseSymbol                 = ?                                
identicalBaseSymbol               = .                                
gapSymbol                         = -                                
[ ProcessTypes ]
ppAlign                           = true                             
ppMuscle                          = true                             
[ AnalysisSettings ]
Gap Penalties                     = ====================             
Gap Open                          = -2.90                            
Gap Extend                        = 0.00                             
Hydrophobicity Multiplier         = 1.20                             
Memory/Iterations                 = ====================             
Max Memory in MB                  = 2048                             
Max Iterations                    = 16                               
Advanced Options                  = ====================             
Cluster Method (Iterations 1,2)   = UPGMA                            
Cluster Method (Other Iterations) = UPGMA                            
Min Diag Length (Lambda)          = 24      
EOF

cat ../data-fasta/*.fasta2 > all-not-aligned.fasta

megacc -a muscle_align_protein.mao -d all-not-aligned.fasta -f Fasta -o all-aligned.fasta


awk '
BEGIN {
  seq = ""
}

/^>/ {
  if (seq != "") {
    print seq
  }
  print $0
  seq = ""
  next
}

{
  gsub(/\r/, "", $0)   # elimina CR por si viene de Windows
  seq = seq $0
}

END {
  if (seq != "") {
    print seq
  }
}
' < all-aligned.fasta > all-aligned.fasta2



cd $local
